//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesEcommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card_
    {
        public int CardId { get; set; }
        public int ClothId { get; set; }
        public int UserId { get; set; }
        public int Quantity { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Cloth Cloth { get; set; }
        public virtual User User { get; set; }
    }
}
